/**
 * Performance Report Generator
 * 
 * Generates markdown summary reports for performance runs.
 */

import { PerformanceRun } from '../models';

/**
 * Generate a markdown summary report for a performance run
 */
export function generateMarkdownReport(run: PerformanceRun): string {
    const { summary, results, suiteName, startTime, endTime, status, environment } = run;

    const lines: string[] = [];

    // Header
    lines.push(`# Performance Report: ${suiteName}`);
    lines.push('');
    lines.push(`**Generated:** ${new Date().toLocaleString()}`);
    lines.push('');

    // Run Info
    lines.push('## Run Information');
    lines.push('');
    lines.push(`| Property | Value |`);
    lines.push(`|----------|-------|`);
    lines.push(`| Status | ${getStatusEmoji(status)} ${status.toUpperCase()} |`);
    lines.push(`| Start Time | ${new Date(startTime).toLocaleString()} |`);
    lines.push(`| End Time | ${new Date(endTime).toLocaleString()} |`);
    lines.push(`| Duration | ${formatDuration(endTime - startTime)} |`);
    if (environment) {
        lines.push(`| Environment | ${environment} |`);
    }
    lines.push('');

    // Summary Statistics
    lines.push('## Summary Statistics');
    lines.push('');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total Requests | ${summary.totalRequests} |`);
    lines.push(`| Successful | ${summary.successCount} (${(summary.successRate * 100).toFixed(1)}%) |`);
    lines.push(`| Failed | ${summary.failureCount} |`);
    lines.push(`| SLA Breaches | ${summary.slaBreachCount} |`);
    lines.push('');

    // Response Time Stats
    lines.push('## Response Time Analysis');
    lines.push('');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Average | ${formatDuration(summary.avgResponseTime)} |`);
    lines.push(`| Minimum | ${formatDuration(summary.minResponseTime)} |`);
    lines.push(`| Maximum | ${formatDuration(summary.maxResponseTime)} |`);
    lines.push(`| P50 (Median) | ${formatDuration(summary.p50)} |`);
    lines.push(`| P95 | ${formatDuration(summary.p95)} |`);
    lines.push(`| P99 | ${formatDuration(summary.p99)} |`);
    lines.push('');

    // Request Breakdown
    if (results.length > 0) {
        lines.push('## Request Breakdown');
        lines.push('');

        // Group by request name - use typeof to infer the result type
        const byRequest = new Map<string, typeof results>();
        for (const r of results) {
            const existing = byRequest.get(r.requestName) || [];
            existing.push(r);
            byRequest.set(r.requestName, existing);
        }

        lines.push(`| Request | Count | Avg | Min | Max | Success Rate |`);
        lines.push(`|---------|-------|-----|-----|-----|--------------|`);

        for (const [name, reqs] of byRequest) {
            const durations = reqs.map(r => r.duration);
            const avg = durations.reduce((a, b) => a + b, 0) / durations.length;
            const min = Math.min(...durations);
            const max = Math.max(...durations);
            const successRate = (reqs.filter(r => r.success).length / reqs.length) * 100;

            lines.push(`| ${name} | ${reqs.length} | ${formatDuration(avg)} | ${formatDuration(min)} | ${formatDuration(max)} | ${successRate.toFixed(1)}% |`);
        }
        lines.push('');
    }

    // Failures section if any
    const failures = results.filter(r => !r.success);
    if (failures.length > 0) {
        lines.push('## Failures');
        lines.push('');
        lines.push(`| Request | Iteration | Status | Error |`);
        lines.push(`|---------|-----------|--------|-------|`);

        for (const f of failures.slice(0, 20)) { // Limit to 20 failures
            lines.push(`| ${f.requestName} | ${f.iteration} | ${f.status} | ${f.error || 'N/A'} |`);
        }

        if (failures.length > 20) {
            lines.push('');
            lines.push(`*...and ${failures.length - 20} more failures*`);
        }
        lines.push('');
    }

    // SLA Breaches
    const breaches = results.filter(r => r.slaBreached);
    if (breaches.length > 0) {
        lines.push('## SLA Breaches');
        lines.push('');
        lines.push(`| Request | Iteration | Duration | Threshold |`);
        lines.push(`|---------|-----------|----------|-----------|`);

        for (const b of breaches.slice(0, 10)) {
            lines.push(`| ${b.requestName} | ${b.iteration} | ${formatDuration(b.duration)} | - |`);
        }

        if (breaches.length > 10) {
            lines.push('');
            lines.push(`*...and ${breaches.length - 10} more breaches*`);
        }
        lines.push('');
    }

    // Footer
    lines.push('---');
    lines.push('');
    lines.push('*Report generated by Dirty Soap Performance Testing*');

    return lines.join('\n');
}

/**
 * Generate a comparison report between two runs
 */
export function generateComparisonReport(runA: PerformanceRun, runB: PerformanceRun): string {
    const lines: string[] = [];

    lines.push('# Performance Comparison Report');
    lines.push('');
    lines.push(`**Generated:** ${new Date().toLocaleString()}`);
    lines.push('');

    lines.push('## Run Comparison');
    lines.push('');
    lines.push(`| Metric | Run A | Run B | Diff |`);
    lines.push(`|--------|-------|-------|------|`);

    const diff = (a: number, b: number) => {
        const d = b - a;
        const pct = ((d / a) * 100).toFixed(1);
        const sign = d > 0 ? '+' : '';
        return `${sign}${pct}%`;
    };

    lines.push(`| Suite | ${runA.suiteName} | ${runB.suiteName} | - |`);
    lines.push(`| Date | ${new Date(runA.startTime).toLocaleDateString()} | ${new Date(runB.startTime).toLocaleDateString()} | - |`);
    lines.push(`| Avg Response | ${formatDuration(runA.summary.avgResponseTime)} | ${formatDuration(runB.summary.avgResponseTime)} | ${diff(runA.summary.avgResponseTime, runB.summary.avgResponseTime)} |`);
    lines.push(`| P95 | ${formatDuration(runA.summary.p95)} | ${formatDuration(runB.summary.p95)} | ${diff(runA.summary.p95, runB.summary.p95)} |`);
    lines.push(`| Success Rate | ${(runA.summary.successRate * 100).toFixed(1)}% | ${(runB.summary.successRate * 100).toFixed(1)}% | ${diff(runA.summary.successRate, runB.summary.successRate)} |`);

    return lines.join('\n');
}

function formatDuration(ms: number): string {
    if (ms < 1000) return `${Math.round(ms)}ms`;
    return `${(ms / 1000).toFixed(2)}s`;
}

function getStatusEmoji(status: string): string {
    switch (status) {
        case 'completed': return '✅';
        case 'aborted': return '⚠️';
        case 'failed': return '❌';
        default: return '⏳';
    }
}

/**
 * Download a markdown report as a file
 */
export function downloadMarkdownReport(content: string, filename: string): void {
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename.endsWith('.md') ? filename : `${filename}.md`;
    link.style.display = 'none';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
